---
### group_vars/CONNECTED_ENDPOINTS.yml

# Definition of connected endpoints in the fabric.
servers:
  # Name of the defined server.
  - name: client1
    # Definition of adapters on the server.
    adapters:
      # Name of the server interfaces that will be used in the description of each interface
      - endpoint_ports: [ client1-eth1, client1-eth2 ]
        # Device ports where the server ports are connected.
        switch_ports: [ Ethernet3, Ethernet3 ]
        # Device names where the server ports are connected.
        switches: [ dc1-leaf1, dc1-leaf2 ]
        # VLANs that will be configured on these ports.
        vlans: 11-12,21-22
        # Native VLAN to be used on these ports.
        native_vlan: 4092
        # L2 mode of the port.
        mode: trunk
        # Spanning tree portfast configuration on this port.
        spanning_tree_portfast: edge
        # Definition of the pair of ports as port channel.
        #port_channel:
        #  # Description of the port channel interface.
        #  description: PortChannel client1
        #  # Port channel mode for LACP.
        #  mode: active

  - name: client2
    adapters:
      - endpoint_ports: [ client2-eth1, client2-eth2 ]
        switch_ports: [ Ethernet4, Ethernet4 ]
        switches: [ dc1-leaf1, dc1-leaf2 ]
        vlans: 11-12,21-22
        native_vlan: 4092
        mode: trunk
        spanning_tree_portfast: edge
        #port_channel:
        #  description: PortChannel client2
        #  mode: active

  # Start of definitions for DC2 (identical to DC1)

  - name: client3
    adapters:
      - endpoint_ports: [ client3-eth1, client3-eth2 ]
        switch_ports: [ Ethernet3, Ethernet3 ]
        switches: [ dc2-leaf1, dc2-leaf2 ]
        vlans: 11-12,21-22
        native_vlan: 4092
        mode: trunk
        spanning_tree_portfast: edge
        #port_channel:
        #  description: PortChannel client3
        #  mode: active

  - name: client4
    adapters:
      - endpoint_ports: [ client4-eth1, client4-eth2 ]
        switch_ports: [ Ethernet4, Ethernet4 ]
        switches: [ dc2-leaf1, dc2-leaf2 ]
        vlans: 11-12,21-22
        native_vlan: 4092
        mode: trunk
        spanning_tree_portfast: edge
        #port_channel:
        #  description: PortChannel client4
        #  mode: active