---
dc_name: DC2

spine:
  defaults:
    platform: vEOS-lab 
    loopback_ipv4_pool: 10.255.128.0/27 
    bgp_as: 65200 

  nodes: 
    - name: dc2-spine1
      id: 11 
      mgmt_ip: 172.20.20.111/24
    - name: dc2-spine2
      id: 12
      mgmt_ip: 172.20.20.112/24

l3leaf:
  defaults:
    platform: vEOS-lab 
    loopback_ipv4_pool: 10.255.128.0/27 
    loopback_ipv4_offset: 2 
    vtep_loopback_ipv4_pool: 10.255.129.0/27 
    uplink_switches: ['dc2-spine1', 'dc2-spine2'] 
    uplink_ipv4_pool: 10.255.255.64/26 
    mlag_interfaces: ['Ethernet5', 'Ethernet6'] 
    mlag_peer_ipv4_pool: 10.255.129.64/27 
    mlag_peer_l3_ipv4_pool: 10.255.129.96/27 
    virtual_router_mac_address: 00:1c:73:00:00:99 
    spanning_tree_priority: 4096 
    spanning_tree_mode: mstp 

  node_groups:
    - group: DC2_LEAF1_2
      bgp_as: 65201
      nodes:
        - name: dc2-leaf1
          id: 1
          mgmt_ip: 192.168.0.121/24
          uplink_switch_interfaces: 
            - Ethernet1 
            - Ethernet1
        - name: dc2-leaf2
          id: 2
          mgmt_ip: 192.168.0.122/24
          uplink_switch_interfaces: 
            - Ethernet2
            - Ethernet2

  nodes:
    - name: dc2-leaf3
      id: 3
      bgp_as: 65203
      evpn_gateway: 
        evpn_l2:
          enabled: true
        evpn_l3:
          enabled: true
          inter_domain: true
        remote_peers: 
          - hostname: dc1-leaf3
      mgmt_ip: 192.168.0.123/24
      uplink_switch_interfaces: 
        - Ethernet3
        - Ethernet3