---
# containerlab_deploy.yml

- name: Create and deploy containerlab topology
  hosts: CONTAINERLAB
  gather_facts: false
  tasks:

    - name: Create and deploy containerlab topology
      ansible.builtin.import_role:
        name: arista.avd.eos_designs_to_containerlab
        tasks_from: deploy
