---
# snapshot.yml

- name: Create snapshot reports from EOS devices
  hosts: FABRIC
  connection: local
  gather_facts: false
  tasks:

    - name: Collect commands
      ansible.builtin.import_role:
        name: arista.avd.eos_snapshot
