---
# validate.yml

- name: Validate state on EOS devices
  hosts: DUAL_DC_FABRIC
  connection: httpapi
  gather_facts: false
  tasks:

    - name: Validate state on EOS devices
      ansible.builtin.import_role:
        name: arista.avd.eos_validate_state
