---
# validate.yml

- name: Validate state on EOS devices
  hosts: FABRIC
  connection: httpapi
  gather_facts: false
  tasks:

    - name: Validate state on EOS devices
      ansible.builtin.import_role:
        name: arista.avd.eos_validate_state
      vars:
        # To enable ANTA
        use_anta: true
        # To save catalogs
        save_catalog: true
